### ISSUE TITLE
create_function deprecated in PHP 7.2.x

### ISSUE THREAD

**Issue by eleazargan** [thedevdojo/wordpress-import#2]
**PHP Version: 7.2.0**

`$pee = preg_replace_callback('/<(script|style).*?<\/\\1>/s', create_function('$matches', 'return str_replace("\n", "<PreserveNewline />", $matches[0]);'), $pee);`

This code at **line 285** in **WordpressImport.php** file produced error. 
I can't use wordpress-import hook with the latest version of PHP. Is this package still being maintained?

**Comment by marktopper** [comment]
This could be easily fixed.
I might have time to make a fix for this.

**Comment by eleazargan** [comment]
Alright thank you!
